### ISSUE TITLE
Dynamically load the Kubernetes contexts so that if they get updated, then Wash will reload them.

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#129]
Currently contexts are loaded from config in the Init function. Move that to the plugin root's List function (where they're used) so it can be cached and reloaded as needed.

**Comment by pop** [comment]
@MikaelSmith @ekinanp I'm interested in contributing to wash. Is this a good issue to help with? If so can I get some pointers about where in the code I might the necessary some changes?

**Comment by MikaelSmith** [comment]
It is, sorry we didn't leave a more complete description!

Wash is structured around a set of plugins that implement its primitives for specific APIs. The Kubernetes plugin lives at https://github.com/puppetlabs/wash/tree/master/plugin/kubernetes. The plugin's [Root](https://godoc.org/github.com/puppetlabs/wash/plugin#Root) implementation lives at https://github.com/puppetlabs/wash/blob/master/plugin/kubernetes/root.go.

Currently contexts are loaded only when [Init](https://github.com/puppetlabs/wash/blob/master/plugin/kubernetes/root.go#L45) is called, which is when Wash starts up; it reads the Kubernetes config and generates a list of k8context objects. This ticket is about moving that work to the [List](https://github.com/puppetlabs/wash/blob/master/plugin/kubernetes/root.go#L94).

We don't have a unit testing framework setup for this section of code yet. One way we do test plugins is by calling `wash validate <plugin>`, which exercises all the unique types implemented by the plugin.

It would be possible to start adding some testing, particularly around this behavior. If you're interested I can work on what that would look like, but it's a bit more complicated.

**Comment by pop** [comment]
Thanks @MikaelSmith. I'll take a look at this code and I'll let you know if I want to help with more than just implementing the feature for this issue. I'm definitely open to helping with tests, but my free ⌛️ time is limited 😞.

**Comment by MikaelSmith** [comment]
Not a problem. https://github.com/puppetlabs/wash/issues/228 is another only slightly more involved one that would be a good next step.
