### ISSUE TITLE
Figure out where wash config. should go. This includes the server config. (wash.yaml) + external plugins (plugins.yaml)

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#132]

**Comment by jdwelch** [comment]
`~/.puppetlabs/wash`?

**Comment by MikaelSmith** [comment]
As in `~/.puppetlabs/wash/wash.yml` and `~/.puppetlabs/wash/plugins.yaml`? I'm not sure plugins needs to be a separate file actually.

**Comment by jdwelch** [comment]
Yup. Single file sounds good to me until there's some reason to make it more complex.
