### ISSUE TITLE
Allow plugins to specify / in their entry names

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#156]
Currently, entries cannot have `/`es in their names, since `/` is the path separator. This is restricting since some APIs could return entry names with `/`es in them or have a hierarchical way of representing paths like `//foo`. For example in S3, `//foo` is modeled as `/:/:foo` (where `:` is the path separator).

Both the API and FUSE do not allow paths like `//foo`. However, we can fix the API to recognize these paths. For FUSE, we can indicate in a `KNOWN ISSUES` section that paths like `//foo` won't work, and that people should use the Wash commands `ls`, `find` when writing their scripts.

**Comment by MikaelSmith** [comment]
We can live without FUSE, but I'd like to understand more how API calls would refer to a path, and how that would affect plugin development.

**Comment by ekinanp** [comment]
Yeah, I'll work on exploring this next once the caching stuff's done + the core plugin docs.

**Comment by ekinanp** [comment]
@MikaelSmith I'm starting to agree with your earlier suggestion on addressing this if it becomes annoying for plugin authors. However I do think we should remove storing the API key in xattr and just compute it ourselves. This way, we don't have to depend on FUSE to retrieve that information.

**Comment by MikaelSmith** [comment]
Not relying on FUSE for the API key is probably a good move. Some optimizations will be hard if we first have to query the filesystem.

**Comment by ekinanp** [comment]
I think there's a pretty easy way to solve this. If we require plugin names to conform to some regex, e.g. like `[A-Za-z_]+`, then in [findEntry](https://github.com/puppetlabs/wash/blob/master/api/helpers.go#L11), if we strip the `/<plugin_name>/` part of the path (which we can do since our Regex guarantees that the plugin name won't contain a `/`), then notice that our path will be of the form (using psuedo-regex notation):
```
<entry_name>(<sep><entry_name>)*
```

where `<sep>` is some arbitrary path separator. Using this, if we change the matching algorithm to something like
```
curGroup = pluginRoot
curEntry = pluginRoot
while path is not empty
  if curGroup is not a Group
    error
  end

  entries = curGroup.List
  for entry in entries do
    if entry.Name().IsPrefixOf(path)
      curGroup = entry
      curEntry = entry
      path = path.StripPrefix(entry.Name()).StripSingleChar
      continue
    end
  end

  return error
end

return curEntry
```

**Comment by ekinanp** [comment]
^ The above algorithm isn't quite correct b/c there could be some ambiguity. In the K8 context case, we'd start with
```
(myproject/127-0-0-1:8443/developer)#<namespace>/pods/pod
```
(the parentheses are meant to de-limit the entry's name, they're not a part of the path).

If we have contexts named `myproject` or `myproject/127-0-0-1:8443/developer`, for example, then the choice would be ambiguous. However, if we re-thought our psuedo-regex as
```
<sep><entry_name><sep>
```

instead, then if we restricted the `<sep>` to conform to some regex, we could extract the `<entry_name>` as-is and do an equality check.

**Comment by ekinanp** [comment]
We could also always include `/` as a path separator and make `PathSeparators()` optional -- if they do define it, the separators for that plugin would be `/` + whatever's returned by `PathSeparators()`.

**Comment by ekinanp** [comment]
I kind of like the longest name approach better. When implementing `find`, we could insert our own path separator on a per-entry basis (e.g. if we had k8 contexts like `myproject` and `myproject/foo`, find could return `/kubernetes/myproject` and `/kubernetes:myproject/foo:`, respectively) (and probably generalize "outputting" a given entry's path to insert the right separator depending on its name).

**Comment by ekinanp** [comment]
We could maybe go with `<sep><entry_name><sep>` and configure it s.t. when Wash encounters `<sep>`, it looks for the matching `<sep>` at the end and strips out the `<entry_name>` for you (idea being that `<sep>` probably won't change). If it can't find a matching `<sep>`, it errors.

**Comment by ekinanp** [comment]
Ok, after discussing this with @MikaelSmith, the approach we're going to take is to transform any `/`'es in entry names to `#` (`#` was chosen because it seems less common than `:` -- if it is also common, we can choose a different character [e.g. `%`]). If `group.List` returns two entries with the same name, Wash will log a warning and omit one of them from the returned array.

This is a temporary fix until we own the shell. Once we own the shell, then we can revisit the `/` => `#` transformation and take a different approach. One possible approach is to let plugin authors specify their own path separators.
