### ISSUE TITLE
Extend `Read` endpoint with `offset and `size` parameters

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#162]
Currently, the `Read` endpoint is limited to reading the entire contents of a given entry. This is limiting, and not very filesystem-y. We should extend it by adding the `offset` and `size` parameters, where `offset` would start reading the content at the specified offset, and `size` indicates the amount of data (in bytes) that's to be read.

Some things to consider:
* What do we do if one or both of `offset` and `size` is not specified? Some sensible options here are:
    * If `offset` is not specified, we start reading at offset 0.
    * If `size` is not specified, then we read all of the content. If the `offset` is specified, we read all of the content starting at the specified offset. Otherwise if `offset` is also not specified, then this reduces to reading the entire content at offset 0, which is idential to the endpoint's current behavior.

* How would this endpoint be invoked by external plugins? The simplest approach would be to invoke a calling convention of
```
<plugin_script> read <path> <state> <offset> <size>
```
but the current `Readable` interface does not cleanly model those semantics. One idea is to change the `Readable` interface to something like
```
type Readable interface {
    ReadContent(ctx, offset, size) ([]byte, error)
}
```
and use the `Size` attribute to determine the content size. This would work well for external plugins, but it has its own issues. For example, it makes it more difficult to write some plugin entries like read-only log/metadata.json files because it'd require a plugin author to explicitly override `Attr` when specifying the `Size` attribute. It also restricts external plugins to having to specify the size attribute as part of `List`'s result, which is also not great.

One idea is to give plugin authors a choice between implementing the existing `Readable` interface, or implementing the new `Readable` interface. Implementing the existing `Readable` interface has the advantage of not requiring plugin authors to override `Attr`.

Anyways, the work in this issue requires some exploration to find a good approach we can take that works for both core and external plugins.

**Comment by ekinanp** [comment]
Hmm, maybe we could get away with the current interface. I think if we changed `Open` to return `Content` instead of a `SizedReader`, where `Content` is described as:
```
type Content interface {
    Size() int64
    Read(ctx, offset, size) ([]byte, error)
}
```

then we can have a helper `plugin.ToContent(<SizedReader>)` (nit: I would like to change `SizedReader` => `SizedReaderAt`).

For external plugins, we can have a `StdoutContent` object whose `Size()` method would return the entry's size attribute, and whose `Read` method would shell out to the plugin script with the calling convention:

```
<plugin_script> read <path> <state> <offset> <size>
```

I think this approach would preserve the simplicity of the existing `Readable` interface while making it possible for external plugins to implement the `Read` endpoint.

NOTE: It's a bit annoying having to require external plugins to specify their entry's attributes w/ `List`. May be worth considering adding an extra `attr` action/query to get this information? That's not important though.

**Comment by MikaelSmith** [comment]
I think https://github.com/puppetlabs/wash/issues/601 will end up superseding this.
