### ISSUE TITLE
Introduce capability to assume IAM roles to the AWS plugin

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#168]
This work requires duplicating the functionality specified in https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html.

**Comment by timidri** [comment]
Just FYI (hope it helps): In awskit we use this script to get temporary credentials:
```
#!/bin/bash
profile=${AWS_PROFILE:-"tse"}

# make sure we have a temporary token
# This will also request your MFA token if needed
echo "Requesting identity with profile $profile"
aws sts get-caller-identity --profile $profile

cachedir=~/.aws/cli/cache
creds_json=$(cat $cachedir/*json)

AWS_ACCESS_KEY_ID=$(echo "$creds_json" | jq -r .Credentials.AccessKeyId)
AWS_SECRET_ACCESS_KEY=$(echo "$creds_json" | jq -r .Credentials.SecretAccessKey)
AWS_SESSION_TOKEN=$(echo "$creds_json"  | jq -r .Credentials.SessionToken)

echo exporting AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

exp=$(echo "$creds_json" | jq -r .Credentials.Expiration)
echo "Current token expires at: $exp"
```

Please note that MFA is required for bastion.

**Comment by timidri** [comment]
Our team is using this tool to generate MFA tokens: http://www.nongnu.org/oath-toolkit/oathtool.1.html

**Comment by timidri** [comment]
Found this: https://github.com/pquerna/otp

**Comment by ekinanp** [comment]
This looks a bit more involved than I thought. Think I'll shelve it for now and then come back to it once we've got some other work out of the way.

**Comment by MikaelSmith** [comment]
It's still worth looking into the the non-interactive MFA handling.
