### ISSUE TITLE
Wash seems to freeze when opened with 'fish' in certain folders (like the wash folder)

### ISSUE THREAD

**Issue by mikkergimenez** [puppetlabs/wash#171]
**Describe the bug**
When running `wash server mnt` in the directory I cloned wash into (~/Dev/wash) it seems to freeze the terminal when I try to take actions in that directory, such as ls.  This also impacted a df -h.  It doesn't happen when I run wash server mnt in a different directory (~/Dev/wash_workspace)

**To Reproduce**
1. Clone wash
2. Run `wash server mnt` in the wash directory
3. open a new terminal, cd into the wash directory and ls.

**Expected behavior**
I expect the ls to complete successfully.

**Logs**
❰mikker❙~❱✘≻ wash ls --debug ~/Dev/wash
Error: unknown flag: --debug
❰mikker❙~❱✘≻ wash ls --loglevel debug ~/Dev/wash
Error: unknown flag: --loglevel

**Environment (please complete the following information):**
Mac OS 10.13.1

**Additional context**
None

**Comment by MikaelSmith** [comment]
Do you use iTerm 2 and zsh? If so, https://github.com/puppetlabs/wash#additional-macos-setup may resolve the issue.

**Comment by mikkergimenez** [comment]
Ahh, no, I am using fish though.

**Comment by MikaelSmith** [comment]
They have similar integration for `fish`. You should try that.

**Comment by MikaelSmith** [comment]
If it works, I'll generalize that recommendation to: 
> If using iTerm2, we recommend installing [iTerm2's shell integration](https://www.iterm2.com/documentation-shell-integration.html) to avoid issue#84.

**Comment by mikkergimenez** [comment]
It doesn't seem to go after installing the iterm2 shell integration.  The symptoms are kinda weird.  It seems like it might have something to do with wash updating all it's internal data, but I don't understand why it's happening when I navigate to the parent directory of mnt.  I do notice while it's hanging that the log in the window that's running wash server mnt is logging a ton.

**Comment by MikaelSmith** [comment]
Ah, maybe you have `fish` integration that's doing a bunch. Can you share some of the logs?

**Comment by MikaelSmith** [comment]
This may not be fish. Found `unexpected newline` trying to authenticate as a role using MFA. I'll try to recreate it.
