### ISSUE TITLE
For useability it would be great if the docker plugin referenced short sha's

### ISSUE THREAD

**Issue by mikkergimenez** [puppetlabs/wash#172]
**Is your feature request related to a problem? Please describe.**
No Problem, just think it would be easier to use if the docker ls showed short sha's, and allowed you to use short sha's on the subcommands

**Describe the solution you'd like**
No Problem, just think it would be easier to use if the docker ls showed short sha's.

**Comment by MikaelSmith** [comment]
Agreed. Short shas, or the given or generated names?

I keep wanting to do names, but there seems to be potential for multiple labels for a running instance so it's not trivial.

**Comment by mikkergimenez** [comment]
Yeah, probably given/generated names, I think Powershell may have some interesting inspiration in the way it handles resource abstractions, and the type of filtering it lets you do on the command line for printing data in table form.  In general I think the ls should provide a bit more inspiration maybe not exactly a docker ps, but most of  the information there, likewise, the metadata.json file should be more natively navigable.

**Comment by MikaelSmith** [comment]
Switched to using container names when present.
