### ISSUE TITLE
Add the `meta` primary to `wash find`

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#192]
The `meta` primary represents a predicate made on the entry's `meta` attribute, which represents the portion of the entry's metadata returned by the plugin's `List` API endpoint (e.g. `DescribeInstances` for EC2 instances; `ListObjects` for S3 objects, etc.). This primary is useful for people who want to filter specific entries via a predicate that isn't captured by the existing `wash find` primaries (e.g. for EC2 instances, the `meta` primary can be used to filter out EC2 instances marked by a specific tag).

**Comment by ekinanp** [comment]
With the `meta` primary, filtering out the right EC2 instances for the AWS reaper should reduce to something like
```
wash find aws/eso/resources/ec2/instances -meta Tags[].Key = termination_date -a -meta Tags[].Value < $(date)
```

(Of course the end result will likely be different, but ^ should illustrate the general idea. Note that `<` and `=` are part of `wash find`'s args).

There's some things we'll need to figure out here.

# If the user specifies the `meta` primary, should we automatically restrict `wash find` to run on a depth of 1 (outputting the appropriate directory that the user should search under if their cwd doesn't have entries whose `meta` schema matches what `wash find` specified?

**Comment by ekinanp** [comment]
Have some ideas around 3. We could modify the `List` endpoint to return a JSON object that's something like:
```
{
  meta_schemas: [
    { "name": "schema1", "schema": <hash representing the metadata's schema>}
  ],
  entries: [
     <bunch of ListEntries here, but they'd include an additional `schema` key specifying their meta attribute's schema>
  ]
}
```

The schema doesn't need to be a full-blown JSON schema, but something that's simple enough to convey the right information. That information would probably include the existing JSON types, but also some additional primitive types like `time`, `mode` for convenience so the munging's less ambiguous. We could compute this information in the API since for each entry, we tend to know the type of it's meta struct (e.g. for AWS EC2 instances, this would be `*ec2Client.Instance`).

**Comment by ekinanp** [comment]
Hmm, we may need a way for the user to tell us the type of value they're comparing. Looks like EC2 tags can be any arbitrary string, so in order to properly handle the AWS reaper use-case, we may need to introduce something like
```
-meta Tags[].Key = termination_date -a -meta Tags[].Value -time < $(date)
```

where `-time` would tell `wash find` that we're comparing two time-values. Maybe properly designing that's simple enough that we don't need any of the schema stuff I mentioned in my earlier comment. However, the schema stuff could be useful if we decide to allow only depth 1 for the `meta` primary b/c then `wash find` in its error message could output directories along the traversed paths whose `meta` attributes satisfy the specified schema. So something like
```
wash find aws -meta Tags[] ...
```

could yield something like
```
Error: Entries in AWS' meta attribute does not have the specified schema. However, the following subdirectories' entries do:
aws/<profile1>/resources/ec2/instances
aws/<profile2>/resources/ec2/instances
...
```

**Comment by ekinanp** [comment]
We should also consider renaming `Entry.Metadata` to something else, maybe `DetailedMetadata` or `Inspect`. The reason for the rename is that `Metadata` and `meta` could contain two separate things. The latter should contain the (partial/raw) metadata returned by the plugin's `List` endpoint, while the former is the entry's full metadata (e.g. for a Docker container, `Metadata` would include the container's platform while `List` does not; for an S3 object, `Metadata` contains much more information about the object than what List returns, so there are good use-cases for keeping the `Metadata` method).

**Comment by MikaelSmith** [comment]
I think we should look to normalize tags/labels somewhat. It's much easier to query `{"termination_date": "..."}` than `{"Key": "termination_date", "Value": "..."}`, and there's no good reason the latter needs to be used. We could do this either on AWS metadata, or as a new type of common attribute.

**Comment by ekinanp** [comment]
Doing this on the AWS metadata as an initial start makes sense to me, because labels is a generic enough concept that it's too early to make it a common attribute. Only concern with the AWS metadata is losing the raw information, but we could add a custom key to handle that (or we could try normalizing it and if people complain, then consider the custom key route). However, the plugin author will still need to provide some type information when invoking the `meta` primary in order for `find` to parse the right thing.

We may still need to handle querying an array of hashes for more complicated structures (e.g. like if you have an array of structs), but I think we can figure out a clean, DSL'ey way to do it.

**Comment by MikaelSmith** [comment]
Tag values are just strings, so the API doesn't give us any clues about their contents either.

**Comment by ekinanp** [comment]
Oh, by type information, I meant that the `wash find` user will likely know the tag value's type. That means we can enable something like `-meta Tags.termination_date --type date --lt $(date)` where `--lt` => `<`.

**Comment by MikaelSmith** [comment]
Oh, yes. Agreed.
