### ISSUE TITLE
Update Kubernetes pods to support multiple containers

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#228]
Add support for multiple containers in a pod. Our current implementation uses a shortcut available only if the pod has a single container; for multiple containers it errors.

Make the pod a directory that lists its containers, with the containers doing all the work the pod currently does (for exec, metadata, etc).

Interacts with #203.

**Comment by vide** [comment]
This would definitely improve my life when using Wash. I've several multi-container pods and I have to resort to `kubectl`. Thanks!

**Comment by pop** [comment]
@MikaelSmith Can I claim this?

**Comment by MikaelSmith** [comment]
Definitely. Implementing this involves adding a List (and ChildSchemas) method to the kubernetes pod struct that lists containers, and moving much of the logic around Open/Stream/Exec to a new container struct.
