### ISSUE TITLE
Support SSH for AWS targets

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#230]
SSM for AWS is not commonly enabled and is pretty slow. It also has very different permission profiles than SSH.

We need to support SSH for AWS targets, and it should probably be the default behavior.

Use golang SSH library initially for speed of development, relying on a correctly configured local ssh-agent. We want to keep open a path for using Bolt's inventory and/or SSH transport later as our customization needs increase. Should also consider using scp for file transfers.

Should we support configuring use of SSM instead of SSH for targets? Should that be on startup, or something you can request for a specific Exec call? Allowing it per Exec introduces extra complexity for everything that builds on Exec, so maybe we should have a separate file target representing the SSM transport.

**Comment by ekinanp** [comment]
Since SSM's mostly useful for a batch exec, I think we should just rip out the existing SSM code and go with SSH. We could always add it back once we get to implementing Batch operations.
