### ISSUE TITLE
Clarify how to see difference in data used with and without Find's 'fullmeta' option

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#281]
Find has a `-fullmeta` primary for resources that require additional requests to get more metadata. However it's not very easy right now to figure out when you should use it.

We should document with `fullmeta` that this is equivalent to `info <path> | jq .attributes.meta` vs `meta <path>`.

We could additionally add a subcommand to show the difference, or provide an option to `meta` to only show the basic metadata instead of "fullmeta".

**Comment by ekinanp** [comment]
Leaning towards having `meta` default to showing the `meta` attribute, and `meta --full` showing the entry's full metadata.

**Comment by MikaelSmith** [comment]
I kind of like full being the default so when people are investigating they see all the potential data. Could make it `--no-full` for symmetry with the fullmeta option.

**Comment by ekinanp** [comment]
Closed by https://github.com/puppetlabs/wash/pull/282
