### ISSUE TITLE
Support enabling/disabling specific plugins in Wash config

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#288]
We could start by adding a single `plugins` key that lists all the plugins you want Wash to load. If the `plugins` key is not provided, then it is reasonable to default to "all" plugins.

Note that the plugins are loaded by the [Server object](https://github.com/puppetlabs/wash/blob/master/cmd/internal/server/core.go), while Wash's config is parsed in https://github.com/puppetlabs/wash/blob/master/cmd/server.go#L87-L119.

The config is documented in https://github.com/puppetlabs/wash/blob/master/website/content/docs/_index.md#config

**Comment by MikaelSmith** [comment]
Should this be expected to disable external plugins as well, or just the core plugins?

**Comment by ekinanp** [comment]
Not sure. Think it's OK to go with core plugins for now, since external plugins are already optional.
