### ISSUE TITLE
Support plugin-specific config in Wash config

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#289]
Examples of plugin-specific config include MFA token durations for the AWS plugin; valid SSH keys for an SSHFS plugin, etc. Ideally, each plugin's config would look something like
```
<plugin_name>:
    <hash describing plugin config>
```

For our SSHFS/AWS examples, we'd have something like:
```
aws:
    mfa_duration: <time>
sshfs:
    valid_keys:
      - key1
      - key2
...
```

Wash would then pass the plugin-specific config along to the appropriate plugin.

This issue is an open-ended design-question. Some things to consider:

* The design should work with external plugins.

* The design should make it easy for plugin authors to access this config. For example, it should be easy for an AWS plugin author to be able to access EC2-specific config when manipulating EC2 instances; S3-specific config when manipulating S3 buckets/objects, etc.

**Comment by timidri** [comment]
@ekinanp This issue is closed, but what is its replacement? Just curious where the plugin-specific config is on the roadmap.

**Comment by ekinanp** [comment]
@timidri Plugin-specific config was merged in https://github.com/puppetlabs/wash/pull/314
