### ISSUE TITLE
Extend the Volume FS helper to enumerate other parts of the remote filesystem

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#290]
Currently, the [Volume FS helper](https://github.com/puppetlabs/wash/blob/master/volume/fs.go) enumerates the contents of the `/var/log` directory. It would be nice if it could enumerate more of a VM/container's remote filesystem, like the root (`/`). However, we should probably make this configurable to avoid inadvertently exposing private locations.

**Comment by ekinanp** [comment]
@MikaelSmith Some more context/ideas around this would be useful. I kind of guessed a bit when writing up the initial description.

**Comment by MikaelSmith** [comment]
This was primarily around performance, less so about private locations. So an alternative here would be improving the Volume implementation to do incremental batch updates. Right now it finds all files within a given hierarchy.
