### ISSUE TITLE
error on Windows Subsystem Linux (WSL)

### ISSUE THREAD

**Issue by leemachine** [puppetlabs/wash#311]
**Describe the bug**
Cannot start WASH on WSL

**To Reproduce**
1. WASH 0.3.1
2. ./wash
3. Unable to start server: listen unix /mnt/c/Users/USERNAME/.cache/wash/wash-api.sock: bind: invalid argument

**Expected behavior**
drop into the WASH shell

**Logs**
none

**Environment (please complete the following information):**
 - OS: Windows 10 build 1809 (WSL)
 - 0.3.1

**Comment by MikaelSmith** [comment]
Thanks for giving this a try! Unfortunately we use libfuse and sockets at the moment, neither of which will work on WSL 1 (and maybe not WSL 2).

There are similar functionality on Windows we can use, details described in #207. If you're interested, I can help figure out where changes would need to be made to do that work. I'm not sure when I might get to it; not in the next month at least.

**Comment by leemachine** [comment]
@MikaelSmith No worries. You focus on Linux/Mac development and I'll try again when WSL 2 comes out. :)
