### ISSUE TITLE
Some containers/VMs could implement the DirProtocol?

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#34]
ls'ing those containers/VMs could look something like:
* If ssh works, then ls would ls the container/VM's root (this would be layering sshfs)
* If ssh does not work, then ls would ls some common log files. The user is still free to search for a specific log file; we could cache these custom log files so that they could be displayed alongside the common ones in a subsequent query.

**Comment by MikaelSmith** [comment]
We started doing this. There are still improvements to make around showing more of the VM contents, captured in #290.
