### ISSUE TITLE
Allow for nil slices/maps in core-plugin JSON schema

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#360]
Consider
```
type Metadata struct {
    Array []string{}
    Map   map[string]string
}
```

Go's default value for `Array` and `Map` is nil. Thus, when  `Metadata` gets marshaled into JSON, its `Array` and `Map` keys will be set to `null`. However, the JSON schema library will treat  `Array`/`Map` as (correctly) being array/object values. Thus if one does something like `wash find foo -m .array -null`, and `foo` has `Metadata` as its metadata schema, then `wash find` will eliminate `foo` from its search path (even though `Array` can be null).

**Comment by ekinanp** [comment]
Don't know if this means re-defining the concept of "Check for a `null` _primitive_ value" to "`null` == `! -exist`", if we should include "null" as a possible type when generating JSON schemas for arrays/maps, or something else entirely.

**Comment by MikaelSmith** [comment]
This doesn't seem likely to come up in practice. If you do run into it let as know and we can revisit it.
