### ISSUE TITLE
Add a `kind` primary to wash find that filters on the kinds of entries

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#404]
This primary only makes sense for plugins that support entry schemas.  The primary would give users a way to expressively filter on specific kinds of entries. This lets them answer higher-level questions like "How many Docker containers/EC2 instances/Kubernetes pods/S3 buckets do I have?". The current way of doing this is a bit magical. For example,
```
find -meta .Created -24h -o -meta .metadata.creationTimestamp -24h
```
returns all Docker containers + Kube pods that started recently. The reason it works is because Docker containers/Kube pods are the only entries whose metadata schemas satisfy the schema predicate, but figuring that out is a bit magical (and the query's fragile because there could be other Wash entries that could have similarly structured metadata schemas). The query also breaks when a user has external plugins that don't provide entry schemas b/c the meta primary, for a better UX, still recurses into those entries (so it'd generate a lot of API requests in the worst-case).

With the kind primary, the query would become
```
find \( -kind 'docker*container' -o -kind 'kube*pod' \) -crtime -24h
```
which is far more expressive. It is also optimized.

**Comment by MikaelSmith** [comment]
I don't think `ctime` is the same. I think we need a separate "created time" attribute.

**Comment by MikaelSmith** [comment]
ctime generally stands for "changed time".

**Comment by ekinanp** [comment]
Filed https://github.com/puppetlabs/wash/issues/405 to address the creation time discrepancy.
