### ISSUE TITLE
Add a proper creation time (crtime) attribute

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#405]
We misunderstood the `ctime` attribute to mean `creation time` when it means `changed time`. We should still keep `ctime` around because it's a filesystem attribute. The work in this issue is to add a separate `crtime` attribute for the creation time, which mirrors some FSes like Ext 3/4 and NTFS, and to clean-up the core plugins to ensure things that once set `ctime` to creation time now set `crtime` to creation time.

The work here would also include adding a `crtime` primary to Wash find so users can filter on it.

**Comment by MikaelSmith** [comment]
bazil/fuse has the `Crtime` attribute, so we should also set it there.
