### ISSUE TITLE
`wash$` prompt in Wash by Example doc is misleading

### ISSUE THREAD

**Issue by caseywilliams** [puppetlabs/wash#432]
**Describe the bug**
I downloaded wash for the first time and followed the Getting Started doc, but the output when I ran the commands was not similar to the output shown in the doc, and I assumed something was wrong.

**To Reproduce**
1. Install wash, make sure fuse is installed
2. Following the Wash by example tutorial, I run `wash`. I see the following output:
```
casey@elflord [~] 19s
$ wash
WARN aws failed to load: could not load any profiles: the /home/casey/.aws/credentials file does not exist 
Welcome to Wash!
  Wash includes several built-in commands: wexec, find, list, meta, tail.
  See commands run with wash via 'whistory', and logs with 'whistory <id>'.
Try 'help'
casey@elflord [~/.cache/wash/mnt772827988]
```
... but the tutorial shows this:
```
$ wash
Welcome to Wash!
  Wash includes several built-in commands: wexec, find, list, meta, tail.
  See commands run with wash via 'whistory', and logs with 'whistory <id>'.
Try 'help'
wash$ cd docker/containers
```
wash seems to work fine -- this issue is only about the `wash$` prompt in the docs and how it differs from the cache dir that actually appears in the (my) prompt

**Expected behavior**
Starting with the "wash by example" doc, it's not immediately clear that the `wash$` prompt shown in the exmaples is not really what should appear on your screen. I think just including a prompt that showed something similar in the docs would make it clear enough.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version/Build number: v0.6.1
 - Cloud target any, doesn't matter

**Comment by caseywilliams** [comment]
FTR, I do think it would be cool if wash replaced my prompt with `wash$` while I was using it

**Comment by MikaelSmith** [comment]
There are a couple things highlighted here we should improve
- the AWS plugin shouldn't warn if there's no AWS config, as that just means they don't use AWS
- we should provide a custom prompt that gives confidence that you're using Wash. It should also include your location in the Wash hierarchy. In Bash that can be accomplished with
```
WASH_BASE=`pwd`
function prompter() { export PS1="wash $(realpath --relative-to=$WASH_BASE $(pwd))$ "; }
prompter
PROMPT_COMMAND=prompter
```
- docs examples should be consistent with the actual behavior
