### ISSUE TITLE
Can't start without analytics

### ISSUE THREAD

**Issue by stahnma** [puppetlabs/wash#451]
## Describe the Bug

I can't use wash because I don't have an `analytics.yaml`. 

```
[0] stahnma@wesley ~> ./wash
WARN aws failed to load: could not load any profiles: the /home/stahnma/.aws/credentials file does not exist
WARN gcp failed to load: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Unable to start server: open /home/stahnma/.puppetlabs/wash/analytics.yaml: no such file or directory
```

## Expected Behavior

It should at least `exit 0` or prompt me with a menu for usage, or something. 

## Steps to Reproduce
1. Download wash
2. Untar.
3. Type `wash`

## Environment
- Version 0.7.0
- Platform: Fedora 30

**Comment by grimradical** [comment]
Reproduced locally!

**Comment by stahnma** [comment]
FWIW, having that file empty works.

**Comment by ekinanp** [comment]
Looks like https://github.com/golang/go/issues/18974 is the reason, i.e. `os.IsNotExist` doesn't work correctly if the `~/.puppetlabs/wash` directory doesn't exist (i.e. https://github.com/puppetlabs/wash/blob/master/analytics/config.go#L59 is the reason). Will push up a fix.
