### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by acidprime** [puppetlabs/wash#492]
## Describe the Bug
Ran through the brew install , loaded wash and then typed ls

Received the following error

```shell
bash: realpath: command not found
```

## Expected Behavior
If `realpath` is needed then homebrew package should install it

## Steps to Reproduce
```shell
brew install puppetlabs/puppet/wash
brew cask install osxfuse
wash . ❯cd aws
wash . ❯ls
```

## Environment
- ProductName:	Mac OS X
- ProductVersion:	10.12.4
- BuildVersion:	16E195
## Additional Context
Installing `brew install coreutils` resolves the issue.

**Comment by MikaelSmith** [comment]
That's fair. I didn't realize realpath is not a core part of macOS.

**Comment by MikaelSmith** [comment]
The quick fix is to `brew install coreutils`. Since that comes with some extra baggage (it installs binaries that conflict with several other packages), I'm going to look into whether there's a portable alternative we could use.
