### ISSUE TITLE
Support AWS Instance Connect

### ISSUE THREAD

**Issue by sampointer** [puppetlabs/wash#505]
## Use Case
[AWS Instance Connect](https://aws.amazon.com/about-aws/whats-new/2019/06/introducing-amazon-ec2-instance-connect/) delegates SSH authentication to IAM. It is pre-configured on new AWS Linux 2 AMIs. Wash should support instance connect in the AWS plugin for SSH operations such as `exec`.

## Describe the Solution You Would Like
It should do this by generating ephemeral keys [in the style of mssh](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#ec2-instance-connect-connecting-ec2-cli) rather than requiring that one [push a key to the instance](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#ec2-instance-connect-connecting-aws-cli).

## Describe Alternatives You've Considered
Whilst one can [manually push keys](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-connect-methods.html#ec2-instance-connect-connecting-aws-cli) to instances with Instance Connect this is less secure than `mssh`-style ephemeral keys.

## Additional Context
None.

**Comment by sampointer** [comment]
I've subsequently noticed that this may be a dupe of https://github.com/puppetlabs/wash/issues/358

**Comment by MikaelSmith** [comment]
I think those are the same thing. Thanks for chiming in! I'll close the other as this is slightly more detailed.
