### ISSUE TITLE
Update actions

### ISSUE THREAD

**Issue by peaceiris** [puppetlabs/wash#507]
Please use the latest version. Check the latest README.

- [Releases · peaceiris/actions-hugo](https://github.com/peaceiris/actions-hugo/releases)
- [Releases · peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages/releases)

**Comment by MikaelSmith** [comment]
We've switched to using Jekyll because we wanted to adopt a layout similar to a site one of our other projects is using. So this is no longer needed.

**Comment by peaceiris** [comment]
I got it. Thank you.
