### ISSUE TITLE
Update wash find examples to be more API-idiomatic

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#514]
Some examples also have errors and are weird. E.g. In `find --help syntax`
```
find kubernetes -daystart -k '*pod' -m .status.startTime -{1d}
    Print out all the Kubernetes pods that started today.
```

doesn't make sense because `-{1d}` is a future time. That should be `-1d`.

**Comment by ekinanp** [comment]
This ticket also involves taking a final pass at the examples that are there to make sure they are correct.

**Comment by MikaelSmith** [comment]
Addressed by https://github.com/puppetlabs/wash/commit/7b5d811a0ae0562a869f87379445858bcca2250d.
