### ISSUE TITLE
GCS bucket objects cannot be read

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/wash#532]
## Description

GCS objects cannot be read; attempting to read a file produces an I/O error on Linux due to an incorrect call to `io.ReadFull`.

## Expected Behavior

Reading a GCS object (with `cat` or some other method) should return the object contents.

## Actual behavior

Reading a file produces the following:

```
wash gcp/system-backups/storage/system-backtops-volta-xggf/snapshots ❯ xxd < cd5d55cb426c7cf489ea22fc46404b2c94e69544c3b2d9e35966aece05d0b949
xxd: Input/output error
```

## Steps to reproduce
1. Create a GCS bucket and object with some contents, ideally with a size not matching the system block size.
2. Attempt to read the file with wash.

## Environment
 - Ubuntu 18.04
 - Golang 1.13
- Wash bb77569

**Comment by adrienthebo** [comment]
Added `Signed-Off-By` to the commit.

**Comment by MikaelSmith** [comment]
S3 objects suffers from the same thing.
