### ISSUE TITLE
GCP plugin creates invalid `compute` directory when compute API is unavailable

### ISSUE THREAD

**Issue by adrienthebo** [puppetlabs/wash#534]
## Description

The GCP plugin will create a `compute` directory even if the GCP Compute Engine API is disabled. If one attempts to list the `compute` directory an error will be emitted:

```
wash gcp/s2-backups ❯ ls compute
WARN FUSE: List /gcp/<project>/compute errored: googleapi: Error 403: Access Not Configured. Compute Engine API has not been used in project <project> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/compute.googleapis.com/overview?project=<project> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured
cannot access 'compute': Input/output error (os error 5) 
```

## Expected Behavior
The `gcp/compute` directory should not be created when the Compute Engine API is not enabled.

## Steps to Reproduce
1. Create a new GCP project with `gcloud projects create ...`
2. Attempt to enter the compute directory with wash

## Environment
 - Wash bb77569
 - Ubuntu 18.04

**Comment by MikaelSmith** [comment]
We have two desires to balance when fixing this:
- we shouldn't list things where we know every operation on it is going to error, as it makes using Wash less enjoyable
- we want it to be clear what functionality is available and can be enabled for a specific provider

We should hide the directory, but we should call out in both logs and documentation when things are hidden and why. It should also be clear from that how to fix it so they're usable.

**Comment by MikaelSmith** [comment]
Ideally we should fix this more broadly, not just in GCP. For now, that means every plugin needs to think about permissions on individual items they list. This could lead to a property on entries that we define, but it's not clear to me yet how it should behave.

**Comment by MikaelSmith** [comment]
I'm going to take the pragmatic approach here where we primarily test permissions on fixed lists. This avoids making list slow when listing something with a lot of elements, like a set of objects in S3 or VMs in GCE, and maps pretty well to API permissions. If you list VMs and don't have permission to do anything on one VM, it makes sense to list the VM as an empty directory (it will still have metadata) and omit specific things you might not have access to (the filesystem, console output).
