### ISSUE TITLE
Signal resources

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#548]
Many resources have state transitions that would be useful to be able to trigger easily, like start/stop/restart a VM or service.

Add a new Signal primitive that plugin entries can implement to allow sending arbitrary signals to a resource. Signal names are case-insensitive.
```
type Signalable interface {
  Signal(context.Context, string) error
}
```

We would like to establish some common conventions for this that make it easier to script without overly constraining the possible applications. As such, add to the plugin documentation around Signalable that `start`, `stop`, and `restart` are common signal names that you should re-use if possible.

Additionally `EntrySchema` should be updated to include a map of supported signals and descriptions of how the entry will respond to them. Those descriptions should be accessible through the `docs` command.

The Wash API should respond to `POST /fs/signal?path=<path>` by invoking Signal on the specified entry and returning whether sending the signal succeeded.

Add a new `signal` command that accepts `signal <signal name> path/to/resource`. It should error and display supported signals if the supplied signal name doesn't match one accepted by the entry at the specified path. It should return after sending the signal; waiting until the signaled operation has completed is an interesting concept, but not one we can do generally for any signal.

See https://docs.google.com/document/d/1NnJ1Qxeu7Sh4_ymOpo0enibKb3V5tzsSsX3H-N0PPDY/edit?usp=sharing for further discussion on the concept.

**Comment by ekinanp** [comment]
Update:

`signal`'s usage was changed to `signal <path> <signal>`. This makes it easier to extend the `signal` command if we ever decide to extend the `signal` action. For example, if we decide to go with `Signal(ctx, signal, opts)`, then the `signal` command can have usage like:

```
signal --help
```
Print the default usage

```
signal <path> --help
```
Print the entry's supported signals/signal groups (to avoid cluttering docs if we add more CRUD primitives later on).

```
signal <path> <signal> --help
```
Print the supported options associated with `<signal>`. For example, if `<path>` is a Docker container, and `<signal>` is `stop`, then this would list all the options for Docker's `containers/stop` endpoint (or whatever other options the Docker plugin author makes available with the `stop` signal).
