### ISSUE TITLE
List and publish to GCP Pub/Sub

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#579]
List available Pub/Sub message topics, and support publishing messages to them by piping a string (a la `echo message > path/to/pubsub/topic`). Also be able to tail a topic to see what messages are being published to it (without consuming them).

## Example

In one terminal, start watching the topic to see messages come in
```
tail -f path/to/topic
```

For a live topic, you should see the messages published to the queue without consuming them (so existing subscriptions still receive them). Not entirely sure if this is possible, a similar idea is to watch whatever logs exist on the topic.

In another terminal, submit a new message to the queue.
```
echo "test message" > path/to/topic
```
This message should then appear in the output from tailing the topic. This provides a simple way to get messages on the queue for testing downstream things that consume them.

## Implementation Notes

Prior art for listing Pub/Sub topics was https://github.com/puppetlabs/wash/blob/d9c5c276ad84a9181a0a9c4aa4a14211d6efa09d/gcp/pubsub.go. We'll need to figure out how to create a [named pipe](http://man7.org/linux/man-pages/man7/fifo.7.html) or something similar with libfuse and how to model it in Wash.

Publishing a message requires a new concept in Wash. We need to dig into this problem a little, then design what the interface should look like.

Note: publishing a message could be a custom command, but POSIX has a file whose concept mirrors a message queue - a FIFO - so we'd rather use that.

**Comment by MikaelSmith** [comment]
Figured out a bit more about watching messages. Every subscription to a topic receives a copy of messages published to that topic. If there are multiple subscribers pulling from a specific subscription, only one of them will receive each message (a message only counts as received once a successful ACK is returned, so its possible for multiple subscribers to get the message but timeout or fail to ACK).

If we want to watch messages published to a topic, we need to setup a temporary subscription that's used only by that Wash command.

**Comment by ekinanp** [comment]
To clarify, the main reason we considered introducing pipes is to allow for pretty-syntax like `echo "message" > /path/to/topic`.

**Comment by MikaelSmith** [comment]
Ran across https://stackoverflow.com/a/32634594/2048059 again. FUSE can't read or write named pipes.
