### ISSUE TITLE
Using xargs with Wash commands fails

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#593]
In zsh or bash, Wash commands are aliases. `xargs` doesn't recognize shell builtins or aliases. So trying to delete all exited docker containers with `find | xargs` results in
```
wash . ❯ find docker/containers -fullmeta -meta .State.Status exited | xargs delete
xargs: delete: No such file or directory
```

I would expect this to work.

**Comment by MikaelSmith** [comment]
We made Wash commands aliases so they would override builtins. When not using bash/zsh we use an executable file at the front of PATH instead. Sounds like we should do both.

**Comment by ekinanp** [comment]
Why do we still have aliases like https://github.com/puppetlabs/wash/blob/master/cmd/internal/shell/bash.go#L31-L34 ? Sorry for bringing this up now, just caught my eye.

**Comment by MikaelSmith** [comment]
To override shell builtins.

**Comment by ekinanp** [comment]
Don't the executable wrappers do that?

**Comment by MikaelSmith** [comment]
Nope. Aliases can override [shell builtins](https://en.wikipedia.org/wiki/Shell_builtin), but shell builtins come before anything on PATH.

**Comment by ekinanp** [comment]
Ah I see. Ok, that makes sense now. Thanks
