### ISSUE TITLE
File lifecycle primitives: Read & Write

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#601]
Finish file lifecycle primitives so we can read and write files.

FUSE operates on blocks of a file. So every request will be for a Read or Write of a length of bytes at an offset. This maps cleanly to Go's `io.ReaderAt` and `io.WriterAt` interfaces. Read operations via FUSE will only read up to the Size attribute of the file, so we need to know the file size before performing any reads.

This has several use cases our primitives need to satisfy:
- Read a file where I know the size.
- I have read-access to a log or other data source with unknown size that I can only read via a Reader or download fully.
- I'm operating on a file through an actual filesystem.
- Writing to an entry with no persistent content like a message queue.
- Update a file.

Implementing this will be done in multiple subissues
- [x] Clearer interface for Read primitives (#619)
- [x] General Write primitive (#620)

**Comment by MikaelSmith** [comment]
The file descriptor use-cases don't seem compelling enough to add `Close`. It's not clear that we need `Sync` yet. And Open is primarily a helper for data that we need to buffer up-front.

So I propose that we make `ReadAt` and `WriteAt` the primary patterns for plugins. As raised in https://github.com/puppetlabs/wash/issues/162, we can use `Content` as a helper concept for files that buffer everything in a single operation. `ReadAt` may be (initially) uncached while `Content` should be cached. `Content` will be called when a file is opened and the result used to update 

```
type Contentable struct {
  Content(context.Context) ([]byte, error) // or the old SizedReader
}

type Readable struct {
  Read(context.Context, []byte, int64) (int, error)
}

type Writable struct {
  Write(context.Context, []byte, int64) (int, error)
}
```

External plugins would be able to implement any of these interfaces as well. Only `Content` is prefetchable (see [External Plugins docs](https://puppetlabs.github.io/wash/docs/external-plugins#entry-json-object)). This represents a breaking change to external plugins.

External plugin invocations would be
```
<plugin_script> read <path> <state> <offset> <size> # data written to stdout and must match supplied size
<plugin_script> write <path> <state> <offset> # data supplied on stdin
<plugin_script> content <path> <state> # data written to stdout
```

**Comment by ekinanp** [comment]
Looks good. Only thing I'd propose is to keep the Go interfaces as symmetric with external plugins as possible and to remove `Content`. So something like

```
Read(ctx, offset, size) ([]byte, fullContent, err)
Write(ctx, data, size)
```

Also, any reason why we're passing `data` to STDIN in external plugin `write` ? Would be nice to keep the invocation symmetric with other stuff.

**Comment by MikaelSmith** [comment]
We pass data to STDIN with write because it's expensive to encode binary data on the command-line (and command-line length is limited).

**Comment by ekinanp** [comment]
Could we break this issue up a bit? I can see at least two chunks:

1. Refactor the Read interfaces. Two cases that need to be handled: (1) Files were size is known -- these should have `ReadAt` semantics and (2) Files were size is known after downloading all content -- the `Download` interface.

2. Properly breakdown all the write scenarios and provide the appropriate implementations.

1 and 2 could also be broken up.

I'm mostly asking because I think breaking stuff up would make it easier for me to think about what's going on too. Read seems to make sense, but I'm having a bit of a hard time understanding all the `Write` stuff to give any valuable feedback on the design.

**Comment by MikaelSmith** [comment]
I'm tempted to leave the Block Write semantics for later. They're an optimization for writing large files, and probably wouldn't see any benefit for many types of updates.

**Comment by ekinanp** [comment]
I'm ok with that.
