### ISSUE TITLE
Linux VIM/VSCode doesn't work with files with unknown content size

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#656]
These applications interpret the file as an empty file thanks to https://github.com/puppetlabs/wash/issues/609. However, this isn't urgent since other tools like `cat`/`less`/`grep` still work, and those kinds of files aren't (commonly) editable.

**Comment by MikaelSmith** [comment]
As I'm working on `Write` operations, we're going to need to be able to update size on an entry so it reflects our local knowledge. I think that work will make this fairly easy to fix as well.
