### ISSUE TITLE
winfo's default output should be more user-friendly and tutorial-like

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#670]
Currently, `winfo` tells you things about the entry like its name, cname, attributes and the supported actions (what you can do with it). Per the discussion in https://github.com/puppetlabs/wash/pull/659#discussion_r357501673, we're thinking of making `winfo` the first point of interaction for a Wash user. Thus, its default output should be a more user-friendly way of expressing all of this information. More experienced Wash users can just do `winfo <entry> -o yaml` to get winfo's parseable form. For multiple paths, e.g. `winfo foo bar`, we can just leave things as-is (default to YAML, output map of `<path> => <info>`).

The ideal, user-friendly `winfo` output should:
* Mention name/cname, attributes, and actions. It should offer example commands that could be used with the latter.
* Mention docs and stree as ways of viewing an entry's documentation (former), and of viewing what's under a given plugin (latter).
* Mention `meta` as a way of viewing the entry's metadata.

In essence, user-friendly `winfo` should try to capture as much of the Fundamentals set of tutorials in the Wash website as possible without being overly verbose.

**Comment by MikaelSmith** [comment]
It feels a little funny to have both docs and (w)info. Should we consider merging them?

**Comment by ekinanp** [comment]
Closed in favor of #671
