### ISSUE TITLE
gcp compute exec uses user from ssh config file

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#725]
My SSH config file has a `Host *` line that sets the default user to root. GCP compute exec uses the user parsed from the GCE SSH files (see https://github.com/puppetlabs/wash/blob/master/plugin/gcp/computeInst.go#L113) and sets that user as the FallbackUser. Thus, the SSH transport will use the `root` user when SSH'ing into the instance (b/c it reads from ~/.ssh/config via https://github.com/puppetlabs/wash/blob/master/transport/ssh.go#L66-L69) instead of the user parsed from my GCE SSH files. Thus, Exec fails because I'm ssh'ing as the wrong user.

I'm filing this issue because exec works fine when I do `gcloud ssh`, meaning GCP probably doesn't read the ~/.ssh/config file for extra info. That means we probably shouldn't either.

WORKAROUND: Just make sure you don't have any `Host` matchers that can conflict with a GCP compute instance's host name. So for me that means removing the `Host *` matcher or changing it to something else like `foo`.

**Comment by ekinanp** [comment]
I wonder why we're setting the parsed user as FallbackUser instead of User? See https://github.com/puppetlabs/wash/blob/master/plugin/gcp/computeInst.go#L137

**Comment by MikaelSmith** [comment]
That does seem like a mistake, I don't have a reason for FallbackUser over User there.

**Comment by MikaelSmith** [comment]
I think my original thinking was that you could use `~/.ssh/config` to change the user, because we don't provide a CLI option for that with `wexec`. But we should also behave consistently with `gcloud ssh`, so I'm fine changing it to fix this.
